### ISSUE TITLE
What about dropping the unsafe?

### ISSUE THREAD

**Issue by RazrFalcon** [programble/ego-tree#12]
Maybe, from the API perspective, it will be better to allow `get(_mut)` to return `Option` therefore making them safe, just like the `Vec` itself. Accessing the vector by the index isn't unsafe, so I don't see a point in making it that way.

You can keep such functionality under the `get(_mut)_unchecked` methods.

The problem is that I'm using NodeId extensively for nodes cycles and it forces me to fill my code with an unnecessary `unsafe`. And since `Tree` is mostly immutable all those id's will be valid anyway.

**Comment by programble** [comment]
Hm. `NodeId` was never meant to be a primary API and I only included it because of how `html5ever` `TreeSink` works.

I also didn't intend for cycles to be valid at all and I think there was/is code that assumes they don't happen.

It's true that `NodeId` remain valid for the lifetime of a `Tree`, but they're also not tied to the lifetime of a `Tree`. I'm not opposed to returning `Option`, but what about the methods on `NodeMut`?

**Comment by RazrFalcon** [comment]
>I also didn't intend for cycles to be valid at all and I think there was/is code that assumes they don't happen.

I use them heavily, and since the Tree is immutable in my case - they always valid.

>what about the methods on NodeMut

I'm not using them. But I think that Option/Result/panic is a better solution. `unsafe` is too extreme for such a case.
